// 基于CMUdict的离线音标转换工具
// 简化版CMUdict，只包含常用单词的音标

const cmuDict = {
  "atmosphere": "AE1 T M AH0 S F IH2 R",
  "hydrosphere": "HH AY1 D R OW0 S F IH2 R",
  "lithosphere": "L IH1 TH AH0 S F IH2 R",
  "oxygen": "AA1 K S AH0 JH AH0 N",
  "oxide": "AA1 K S AY0 D",
  "carbon": "K AA1 R B AH0 N",
  "dioxide": "D AY2 AA1 K S AY0 D",
  "hydrogen": "HH AY1 D R AH0 DZH AH0 N",
  "core": "K AO1 R",
  "crust": "K R AH1 S T",
  "mantle": "M AE1 N T AH0 L",
  "longitude": "L AA1 NG G IH0 T UH0 D",
  "latitude": "L AE1 T AH0 T UH0 D",
  "altitude": "AE2 L T AH0 T UH0 D",
  "horizon": "HH AH0 R AY1 Z AH0 N",
  "disaster": "D IH0 Z AE1 S T ER0",
  "mishap": "M IH1 SH AE0 P",
  "catastrophic": "K AE2 T AH0 S T R AH1 F IH0 K",
  "calamity": "K AH0 L AE1 M AH0 T IY0",
  "endanger": "EH1 N D EY2 N JH ER0",
  "jeopardise": "JH EH1 P ER0 D AY2 Z",
  "destructive": "D IH0 S T R AH1 K T IH0 V",
  "greenhouse": "G R IY1 N HH AW2 S",
  "phenomenon": "F AH0 N AA1 M AH0 N AA0 N",
  "pebble": "P EB1 AH0 L",
  "magnet": "M AE1 G N AH0 T",
  "ore": "AO1 R",
  "mineral": "M IH1 N ER0 AH0 L",
  "marble": "M AA1 R B AH0 L",
  "quartz": "K W AO1 R T S",
  "granite": "G R AE1 N AH0 T",
  "breeze": "B R IY1 Z",
  "gust": "G AH1 S T",
  "gale": "G EY1 L",
  "hurricane": "HH ER1 AH0 K EY2 N",
  "tornado": "T AO1 R N EY2 D OW0",
  "typhoon": "T AY1 F UH0 N",
  "monsoon": "M AA1 N S UH0 N",
  "volcano": "V AA1 L K EY2 N OW0",
  "erupt": "IH2 R AH1 P T",
  "magma": "M AE1 G M AH0",
  "smog": "S M AA1 G",
  "fume": "F Y UW1 M",
  "mist": "M IH1 S T",
  "tsunami": "T S UW2 N AA1 M IY0",
  "flooding": "F L AH1 D IH0 NG",
  "torrent": "T AO1 R AH0 N T",
  "drought": "D R AW1 T",
  "earthquake": "ER1 TH K W EY2 K",
  "seismic": "S AY2 Z M IH0 K",
  "avalanche": "AE2 V AH0 L AE1 N CH",
  "terrain": "T ER1 EY2 N",
  "landscape": "L AE1 N D SK EY2 P",
  "continent": "K AA1 N T AH0 N AH0 N T",
  "cave": "K EY1 V",
  "cliff": "K L IH1 F",
  "glacier": "G L AE1 SH ER0",
  "swamp": "S W AA1 M P",
  "delta": "D EH1 L T AH0",
  "plain": "P L EY1 N",
  "plateau": "P L AE1 T OW2",
  "oasis": "OW2 EY1 S IH0 S",
  "globe": "G L OW1 B",
  "hemisphere": "HH EM1 AH0 S F IH2 R",
  "equator": "IH1 K W EY2 T ER0",
  "equal": "IY1 K W AH0 L",
  "arctic": "AA1 R K T IH0 K",
  "antarctic": "AE2 N T AA1 R K T IH0 K",
  "pole": "P OW1 L",
  "polar": "P OW2 L ER0",
  "axis": "AE1 K S AH0 S",
  "deteriorate": "D IH0 T IH1 R IY0 EY2 T",
  "aggravate": "AE1 G R AH0 V EY2 T",
  "degrade": "D IH0 G R EY1 D",
  "upgrade": "AH1 P G R EY2 D",
  "erode": "IH1 R OW2 D",
  "atlantic": "AH0 T L AE1 N T IH0 K",
  "ocean": "OW1 SH AH0 N",
  "pacific": "P AH0 S IH1 F IH0 K",
  "marine": "M ER1 IY0 N",
  "navigation": "N AE1 V AH0 G EY2 SH AH0 N",
  "gulf": "G AH1 L F",
  "beach": "B IY1 CH",
  "coast": "K OW1 S T",
  "shore": "SH AO1 R",
  "tide": "T AY1 D",
  "current": "K ER1 AH0 N T",
  "brook": "B R UH1 K",
  "stream": "S T R IY1 M",
  "source": "S AO1 R S",
  "shallow": "SH AE1 L OW0",
  "superficial": "S UW0 P ER1 F IH0 SH AH0 L",
  "flat": "F L AE1 T",
  "smooth": "S M UH1 DH",
  "rough": "R AH1 F",
  "sandy": "S AE1 N D IY0",
  "stony": "S T OW1 N IY0",
  "vertical": "V ER1 T IH0 K AH0 L",
  "steep": "S T IY1 P",
  "parallel": "P AE1 R AH0 L EL0",
  "narrow": "N AE1 R OW0",
  "mainland": "M EY1 N L AE2 N D",
  "peninsula": "P AH0 N IH1 N S AH0 L AH0",
  "climate": "K L AY2 M AH0 T",
  "weather": "W EH1 DH ER0",
  "meteorology": "M IY2 T IY0 AH0 R AA1 L AH0 JH IY0",
  "mild": "M AY1 L D",
  "heating": "HH IY1 T IH0 NG",
  "moderate": "M AA1 D ER0 AH0 T",
  "warm": "W AO1 R M",
  "thermal": "TH ER1 M AH0 L",
  "tropics": "T R AA1 P IH0 K S",
  "arid": "AE1 R IH0 D",
  "moist": "M OY1 S T",
  "damp": "D AE1 M P",
  "humid": "HH Y UW1 M IH0 D",
  "snowy": "S N OW1 IY0",
  "frost": "F R AO1 S T",
  "hail": "HH EY1 L",
  "thaw": "TH AO1",
  "chill": "CH IH1 L",
  "freeze": "F R IY1 Z",
  "frigid": "F R IH1 JH IH0 D",
  "tremble": "T R EH1 M B AH0 L",
  "shiver": "SH IH1 V ER0",
  "thunder": "TH AH1 N D ER0",
  "lightning": "L AY1 T N IH0 NG",
  "stormy": "S T AO1 R M IY0",
  "downpour": "D AW1 N P AO2 R",
  "rainfall": "R EY1 N F AO2 L",
  "sprinkle": "S P R IH1 NG K AH0 L",
  "rainbow": "R EY1 N B OW0",
  "shower": "SH AW1 ER0",
  "celsius": "S EH1 L S IY0 AH0 S",
  "temperature": "T EH1 M P ER0 AH0 CH ER0",
  "forecast": "F AO1 R K AE2 S T",
  "peak": "P IY1 K",
  "mount": "M AW1 N T",
  "mountain": "M AW1 N T AH0 N",
  "range": "R EY1 N JH",
  "ridge": "R IH1 JH",
  "slope": "S L OW1 P",
  "valley": "V AE1 L IY0",
  "hillside": "H IH1 L S AY2 D",
  "overlook": "OW1 V ER0 L UH2 K",
  "southern": "S AH1 DH ER0 N",
  "southeast": "S AW2 TH IY1 S T",
  "southwest": "S AW2 TH W ES1 T",
  "northeast": "N AO2 R TH IY1 S T",
  "northwest": "N AO2 R TH W ES1 T",
  "eastern": "IY1 S T ER0 N",
  "oriental": "AO2 R IY1 EH0 N T L",
  "inevitable": "IH2 N EH1 V AH0 T AH0 B AH0 L",
  "irreversible": "IH2 R IH0 V ER1 S AH0 B AH0 L",
  "irregularly": "IH2 R EH1 G Y AH0 L ER0 L IY0",
  "inappropriate": "IH2 N AH0 P R OW1 P R IY0 AH0 T",
  "abnormal": "AE1 B N AO2 R M AH0 L",
  "sediment": "S EH1 D IH0 M AH0 N T",
  "silt": "S IH1 L T",
  "muddy": "M AH1 D IY0",
  "clay": "K L EY1",
  "dirt": "D ER1 T",
  "rural": "R UR1 AH0 L",
  "suburb": "S AH1 B ER0 B",
  "outskirts": "AW1 T SK ER0 T S",
  "remote": "R IH1 M OW2 T",
  "desolate": "D EH1 S AH0 L AH0 T",
  "distant": "D IH1 S T AH0 N T",
  "adjacent": "AH0 JH EY1 S AH0 N T",
  "toxic": "T AA1 K S IH0 K",
  "pollution": "P AH0 L UW2 SH AH0 N",
  "pollutant": "P AH0 L UW2 T AH0 N T",
  "contaminate": "K AH0 N T AE1 M AH0 N EY2 T",
  "geology": "JH IY1 AA2 L AH0 JH IY0",
  "border": "B AO1 R D ER0",
  "margin": "M AA1 R JH AH0 N",
  "fringe": "F R IH1 N JH",
  "plate": "P L EY1 T",
  "debris": "D AH0 B R IY1",
  "crack": "K R AE1 K",
  "gap": "G AE1 P",
  "splendid": "S P L EH1 N D IH0 D",
  "grand": "G R AE1 N D",
  "magnificent": "M AE1 G N IH0 F IH0 S AH0 N T",
  "super": "S UW1 P ER0",
  "interesting": "IH2 N T ER0 EH1 S T IH0 NG",
  "dramatic": "D R AE2 M AH0 T IH0 K",
  "wilderness": "W IH1 L D ER0 N AH0 S",
  "desert": "D EH1 Z ER0 T",
  "deforest": "D IY2 F AO1 R IH0 S T",
  "barren": "B AE1 R AH0 N",
  "fertile": "F ER1 T AH0 L",
  "fertilise": "F ER1 T AH0 L AY2 Z",
  "solar": "S OW1 L ER0",
  "lunar": "L UW1 N ER0",
  "calendar": "K AE1 L AH0 N D ER0",
  "sunrise": "S AH1 N R AY2 Z",
  "sunset": "S AH1 N S EH2 T",
  "eclipse": "IH2 K L IH1 P S",
  "dusk": "D AH1 S K",
  "heaven": "HH EH1 V AH0 N",
  "paradise": "P AE1 R AH0 D AY2 S",
  "sunshine": "S AH1 N SH AY2 N",
  "shade": "SH EY1 D",
  "shadow": "SH AE1 D OW0",
  "vapour": "V EY1 P ER0",
  "evaporate": "IH2 V AE1 P ER0 EY2 T",
  "circulate": "S ER1 K Y AH0 L EY2 T",
  "precipitate": "P R IH2 S IH1 P AH0 T EY2 T",
  "reservoir": "R EH1 Z ER0 V W AA2 R",
  "waterfall": "W AA1 T ER0 F AO2 L",
  "fountain": "F AW1 N T AH0 N",
  "spring": "S P R IH1 NG",
  "dew": "D UW1",
  "pour": "P AO1 R",
  "drain": "D R EY1 N",
  "drip": "D R IH1 P",
  "drown": "D R AW1 N",
  "blow": "B L OW1",
  "puff": "P AH1 F",
  "gush": "G UH1 SH",
  "dense": "D EH1 N S",
  "intensity": "IH2 N T EH1 N S AH0 T IY0",
  "intensive": "IH2 N T EH1 N S IH0 V",
  "emerge": "IH2 M ER1 JH",
  "flash": "F L AE1 SH",
  "float": "F L OW1 T",
  "environment": "EH2 N V AY0 R AH0 N M AH0 N T",
  "surrounding": "S ER2 AW1 N D IH0 NG",
  "condition": "K AH2 N D IH1 SH AH0 N",
  "situation": "S IH2 CH UW1 EY1 SH AH0 N",
  "nature": "N EY1 CH ER0",
  "natural": "N AE1 CH ER0 AH0 L",
  "artificial": "AA1 R T IH0 F IH0 SH AH0 L",
  "synthetic": "S IH1 N TH EH2 T IH0 K",
  "petrol": "P EH1 T R AH0 L",
  "gas": "G AE1 S",
  "photosynthesis": "F OW2 T OW1 S IH1 N TH AH0 S IH0 S",
  "respire": "R IH1 S P AY2 R",
  "vegetation": "V EH1 JH AH0 T EY2 SH AH0 N",
  "herb": "HH ER1 B",
  "perennial": "P ER2 EN1 IY0 AH0 L",
  "botany": "B AA1 T AH0 N IY0",
  "ecology": "IH2 K AA1 L AH0 JH IY0",
  "ecosystem": "EH2 K OW1 S IH0 S T AH0 M",
  "horticulture": "HH AO2 R T IH1 K AH0 L CH ER0",
  "organism": "AO1 R G AH0 N IH2 Z AH0 M",
  "genetics": "JH EH1 N EH0 T IH2 K S",
  "mutation": "M Y UW1 T EY2 SH AH0 N",
  "variation": "V ER1 IY0 EY2 SH AH0 N",
  "diversity": "D AH2 V ER1 S AH0 T IY0",
  "classify": "K L AE1 S AH0 F AY2",
  "reproduce": "R IY2 P R AH0 D UW1 S",
  "evolve": "IH2 V AA1 L V",
  "fluctuate": "F L UH2 K CH UW1 EY2 T",
  "cultivate": "K AH1 L T AH0 V EY2 T",
  "reclaim": "R IY2 K L EY1 M",
  "sow": "S OW1",
  "harvest": "HH AA1 R V AH0 S T",
  "pluck": "P L UH1 K",
  "pick": "P IH1 K",
  "yield": "Y IY1 L D",
  "rear": "R IH1 R",
  "arable": "EH1 R AH0 B AH0 L",
  "plough": "P L AW1",
  "spade": "S P EY1 D",
  "rake": "R EY1 K",
  "stack": "S T AE1 K",
  "heap": "HH IY1 P",
  "bundle": "B AH1 N D AH0 L",
  "bunch": "B AH1 N CH",
  "vase": "V EY1 S",
  "sunlight": "S AH1 N L AY2 T",
  "fungus": "F AH1 NG G AH0 S",
  "mould": "M OW1 L D",
  "pollen": "P AA1 L AH0 N",
  "germinate": "JH ER1 M AH0 N EY2 T",
  "seed": "S IY1 D",
  "burgeon": "B ER1 JH AH0 N",
  "bud": "B AH1 D",
  "flower": "F L AW1 ER0",
  "blossom": "B L AA1 S AH0 M",
  "bloom": "B L UW1 M",
  "scent": "S EH1 N T",
  "aromatic": "EH2 R AH0 M AE1 T IH0 K",
  "ripen": "R AY1 P AH0 N",
  "fruit": "F R UW1 T",
  "wither": "W IH1 DH ER0",
  "decompose": "D IY2 K AH0 M P OW1 Z",
  "rot": "R AA1 T",
  "decay": "D IH2 K EY1",
  "stale": "S T EY1 L",
  "rainforest": "R EY1 N F AO2 R IH0 S T",
  "jungle": "J AH1 NG G AH0 L",
  "plantation": "P L AE1 N T EY2 SH AH0 N",
  "field": "F IY1 L D",
  "terrace": "T ER1 AH0 S",
  "timber": "T IH1 M B ER0",
  "charcoal": "CH AA1 R K OW2 L",
  "log": "L AO1 G",
  "forestry": "F AO1 R IH0 S T R IY0",
  "branch": "B R AE1 N CH",
  "trunk": "T R AH1 NG K",
  "bough": "B AW1",
  "root": "R UW1 T",
  "hay": "HH EY1",
  "straw": "S T R AW1",
  "reed": "R IY1 D",
  "thorn": "TH AO1 R N",
  "weed": "W IY1 D",
  "grass": "G R AE1 S",
  "meadow": "M EH1 D OW2",
  "lawn": "L AO1 N",
  "olive": "AA1 L IH0 V",
  "pine": "P AY1 N",
  "vine": "V AY1 N",
  "violet": "V AY1 AH0 L IH0 T",
  "tulip": "T Y UW1 L IH0 P",
  "mint": "M IH1 N T",
  "reef": "R IY1 F",
  "alga": "AE1 L G AH0",
  "enzyme": "EH1 N Z AY2 M",
  "catalyst": "K AE1 T AH0 L IH2 S T",
  "release": "R IH2 L IY1 S",
  "emission": "IH2 M IH1 SH AH0 N",
  "absorb": "AH0 B S AO1 R B",
  "circulation": "S ER2 K Y AH0 L EY1 SH AH0 N",
  "exceed": "IH2 K S IY1 D",
  "uptake": "UH1 P T EY2 K",
  "nutrient": "N UW1 T R IY0 AH0 N T",
  "energy": "EH2 N ER1 JH IY0",
  "surroundings": "S ER2 AW1 N D IH0 NG Z",
  "counterbalance": "K AW2 N T ER0 B AE1 L AH0 N S",
  "mechanism": "M EH2 K AH0 N IH1 Z AH0 M",
  "preserve": "P R IH2 Z ER1 V",
  "conservation": "K AH2 N S ER1 V EY1 SH AH0 N",
  "extinguish": "IH2 K S T IH1 NG GW IH0 SH",
  "destruct": "D IH0 S T R AH1 K T",
  "ruin": "R UW1 IH0 N",
  "perish": "P ER1 IH0 SH",
  "demolish": "D IH0 M AA1 L IH0 SH",
  "infringe": "IH2 N F R IH1 N JH",
  "undermine": "UH2 N D ER1 M AY2 N",
  "extinction": "IH2 K S T IH1 NG K SH AH0 N",
  "pattern": "P AE1 T ER0 N",
  "outcome": "AW1 T K AH2 M",
  "impact": "IH1 M P AE2 K T",
  "seasonal": "S IY1 Z AH0 N AH0 L",
  "experimental": "EH2 K S P ER1 IH0 M EN1 T AH0 L",
  "favourable": "F EY1 V ER0 AH0 B AH0 L",
  "productive": "P R AH0 D AH2 K T IH0 V",
  "feed": "F IY1 D",
  "efficient": "IH2 F IH1 SH AH0 N T",
  "effective": "IH2 F EH1 K T IH0 V",
  "considerable": "K AH2 N S IH1 D ER0 AH0 B AH0 L",
  "massive": "M AE1 S AH0 V",
  "immense": "IH1 M EH2 N S",
  "optimal": "AA1 P T AH0 M AH0 L",
  "biologist": "B AY1 AA2 L AH0 JH IH0 S T",
  "zoologist": "Z OW1 AA2 L AH0 JH IH0 S T",
  "ecologist": "EH2 K AA1 L AH0 JH IH0 S T",
  "botanist": "B AA1 T AH0 N IH0 S T",
  "mammal": "M AE1 M AH0 L",
  "primate": "P R AY1 M EY2 T",
  "vertebrate": "V ER1 T AH0 B R EY2 T",
  "reptile": "R EH1 P T AH0 L",
  "amphibian": "AE1 M F IH0 B IY0 AH0 N",
  "carnivore": "K AA1 R N IH0 V AO2 R",
  "herbivore": "HH ER1 B IH0 V AO2 R",
  "creature": "K R IY1 CH ER0",
  "wildlife": "W AY2 L D L AY1 F",
  "fauna": "F AO1 N AH0",
  "flora": "F L AO1 R AH0",
  "species": "S P IY1 SH IY0 Z",
  "flock": "F L AA1 K",
  "herd": "HH ER1 D",
  "swarm": "S W AO1 R M",
  "throng": "TH R AO1 NG",
  "crowd": "K R AW1 D",
  "beast": "B IY1 S T",
  "brute": "B R UW1 T",
  "cruel": "K R UW1 AH0 L",
  "subgroup": "S AH1 B G R UW2 P",
  "breed": "B R IY1 D",
  "interbreed": "IH2 N T ER0 B R IY1 D",
  "hybridize": "HH AY1 B R AH0 D AY2 Z",
  "proliferate": "P R AH0 L IH1 F ER0 EY2 T",
  "sterility": "S T EH1 R IH0 L IH0 T IY0",
  "mate": "M EY1 T",
  "courtship": "K AO1 R T SH IH2 P",
  "lay": "L EY1",
  "hatch": "HH AE1 CH",
  "brood": "B R UH1 D",
  "spawn": "S P AW1 N",
  "mature": "M AH0 T Y UW1 R",
  "originate": "AH2 R IH1 JH AH0 N EY2 T",
  "derive": "D IH0 R AY1 V",
  "stem": "S T EH1 M",
  "ancestor": "AE1 N S EH2 S T ER0",
  "descendant": "D IH2 S EH1 N D AH0 N T",
  "offspring": "AO1 F S P R IH2 NG",
  "skin": "S K IH1 N",
  "claw": "K L AW1",
  "paw": "P AO1",
  "beak": "B IY1 K",
  "fin": "F IH1 N",
  "wing": "W IH1 NG",
  "feather": "F EH1 DH ER0",
  "fur": "F ER1",
  "bristle": "B R IH1 S AH0 L",
  "curl": "K ER1 L",
  "insect": "IH1 N S EH2 K T",
  "worm": "W ER1 M",
  "pest": "P EH1 S T",
  "parasite": "P AE1 R AH0 S AY2 T",
  "spider": "S P AY1 D ER0",
  "butterfly": "B AH1 T ER0 F L AY2",
  "mosquito": "M AH1 S K IY0 T OW2",
  "cricket": "K R IH1 K IH0 T",
  "penguin": "P EH1 NG G W IH2 N",
  "seal": "S IY1 L",
  "tortoise": "T AO1 R T AH0 S",
  "turtle": "T ER1 T AH0 L",
  "whale": "W EY1 L",
  "kangaroo": "K AE1 NG G AH0 R UW2",
  "camel": "K AE1 M AH0 L",
  "panda": "P AE1 N D AH0",
  "elephant": "EH1 L AH0 F AH0 N T",
  "ivory": "AY1 V ER0 IY0",
  "horn": "HH AO1 R N",
  "bear": "B EH1 R",
  "wolf": "W UH1 L F",
  "dragon": "D R AE1 G AH0 N",
  "fox": "F AA1 K S",
  "cub": "K AH1 B",
  "calf": "K AE1 F",
  "pup": "P AH1 P",
  "lamb": "L AE1 M",
  "cattle": "K AE1 T AH0 L",
  "ox": "AA1 K S",
  "bull": "B UH1 L",
  "buffalo": "B AH1 F AH0 L OW2",
  "horse": "HH AO1 R S",
  "zebra": "Z EH1 B R AH0",
  "donkey": "D AA1 NG K IY0",
  "saddle": "S AE1 D AH0 L",
  "harness": "HH AA1 R N IH0 S",
  "falcon": "F AE1 L K AH0 N",
  "hawk": "HH AW1 K",
  "eagle": "IY1 G AH0 L",
  "owl": "AW1 L",
  "swallow": "S W AA1 L OW0",
  "pigeon": "P IH1 JH AH0 N",
  "sparrow": "S P AE1 R OW0",
  "crow": "K R OW1",
  "swan": "S W AA1 N",
  "goose": "G UW1 S",
  "cock": "K AA1 K",
  "mouse": "M AW1 S",
  "rat": "R AE1 T",
  "squirrel": "S K W ER1 AH0 L",
  "hare": "HH ER1",
  "frog": "F R AA1 G",
  "behaviour": "B IH0 HEY2 V Y AH0 R",
  "bite": "B AY1 T",
  "sting": "S T IH1 NG",
  "bark": "B AA1 R K",
  "roar": "R AO1 R",
  "rub": "R AH1 B",
  "creep": "K R IY1 P",
  "crawl": "K R AO1 L",
  "habitat": "HH AE1 B AH0 T AE2 T",
  "nest": "N EH1 S T",
  "hive": "HH AY1 V",
  "cell": "S EH1 L",
  "cage": "K EY1 JH",
  "stable": "S T EY1 B AH0 L",
  "barn": "B AA1 R N",
  "hedge": "HH EH1 JH",
  "barrier": "B AE1 R IY0 ER0",
  "bar": "B AA1 R",
  "anatomy": "AH0 N AE1 T AH0 M IY0",
  "epidemic": "EH2 P IH1 D EM1 IH0 K",
  "germ": "JH ER1 M",
  "bacteria": "B AE1 K T IH0 R IY2 AH0",
  "virus": "V AY1 R AH0 S",
  "microbe": "M AY2 K R OW1 B",
  "metabolism": "M EH1 T AH0 B AH0 L IH2 Z AH0 M",
  "secrete": "S IH2 K R IY1 T",
  "excrete": "EH2 K S K R IY1 T",
  "devour": "D IH0 V AW2 R",
  "instinct": "IH1 N S T IH0 NG K T",
  "intuitive": "IH2 N T UW1 IH0 T IH0 V",
  "intuition": "IH2 N T UW1 IH0 SH AH0 N",
  "potential": "P AH2 T EN1 SH AH0 L",
  "intelligence": "IH2 N T EH1 L AH0 JH EH1 N S",
  "functional": "F AH1 NG K SH AH0 N AH0 L",
  "sensitive": "S EN1 S AH0 T IH0 V",
  "flexible": "F L EH1 K S AH0 B AH0 L",
  "acoustic": "AH0 K UH1 S T IH0 K",
  "optical": "AA1 P T IH0 K AH0 L",
  "nocturnal": "N AA2 K T ER1 N AH0 L",
  "dormant": "D AO1 R M AH0 N T",
  "hibernation": "HH AY2 B ER1 N EY1 SH AH0 N",
  "track": "T R AE1 K",
  "trace": "T R EY1 S",
  "alternate": "AO1 L T ER2 N EY1 T",
  "prey": "P R EY1",
  "predator": "P R EH1 D AH0 T ER0",
  "victim": "V IH1 K T IH0 M",
  "captive": "K AE1 P T IH0 V",
  "captivate": "K AE1 P T AH0 V EY2 T",
  "defensive": "D IH0 F EN1 S IH0 V",
  "defend": "D IH0 F EH1 N D",
  "undergo": "UH2 N D ER1 G OW2",
  "suffer": "S AH1 F ER0",
  "vulnerable": "V UH2 L N ER1 AH0 B AH0 L",
  "subsistence": "S AH2 B S IH1 S T AH0 N S",
  "exist": "IH1 G Z IH2 S T",
  "existence": "IH1 G Z IH2 S T AH0 N S",
  "exterminate": "EH2 K S T ER1 M AH0 N EY2 T",
  "tame": "T EY1 M",
  "keeper": "K IY1 P ER0",
  "shepherd": "SH EH1 P ER0 D",
  "sheepdog": "SH IY1 P D AO1 G",
  "galaxy": "G AE1 L AH0 K S IY0",
  "cosmos": "K AA1 Z M AA0 S",
  "universe": "Y UW2 N AH0 V ER1 S",
  "interstellar": "IH2 N T ER0 ST EL1 ER0",
  "terrestrial": "T ER1 EH0 S T R IY2 AH0 L",
  "celestial": "S AH0 L EH1 S CH AH0 L",
  "astronomy": "AH2 S T R AA1 N AH0 M IY0",
  "astrology": "AH2 S T R AA1 L AH0 JH IY0",
  "astronaut": "AE1 S T R AH0 N AW2 T",
  "comet": "K AA1 M IH0 T",
  "meteorite": "M IY1 T IY0 R AY2 T",
  "crater": "K R EY1 T ER0",
  "dust": "D AH1 S T",
  "ash": "AE1 SH",
  "envelope": "EH1 N V AH0 L OW2 P",
  "chunk": "CH AH1 NG K",
  "spacecraft": "S P EY1 S K R AE2 F T",
  "spaceship": "S P EY1 S SH IH2 P",
  "probe": "P R OW1 B",
  "module": "M AA1 D Y UW2 L",
  "propulsion": "P R AH0 P UH2 L SH AH0 N",
  "pressure": "P R EH1 SH ER0",
  "dynamics": "D AY2 N AE1 M IH0 K S",
  "motion": "M OW1 SH AH0 N",
  "vent": "V EH1 N T",
  "tail": "T EY1 L",
  "curve": "K ER1 V",
  "exploration": "EH2 K S P L AO1 R EY1 SH AH0 N",
  "expedition": "EH2 K SP IH1 D IH2 SH AH0 N",
  "flyby": "F L AY1 B AY2",
  "observatory": "AH2 B Z ER1 V AH0 T AO2 R IY0",
  "telescope": "T EH1 L AH0 S K OW2 P",
  "spectacle": "S P EH1 K T AH0 K AH0 L",
  "orbit": "AO1 R B IH2 T",
  "ecliptic": "IH2 K L IH1 P T IH0 K",
  "diameter": "D AY2 AE1 M IH0 T ER0",
  "radius": "R EY1 D IY0 AH0 S",
  "substance": "S AH1 B S T AH0 N S",
  "composition": "K AA2 M P OW1 Z IH0 SH AH0 N",
  "compound": "K AA1 M P AW2 N D",
  "fossil": "F AA1 S AH0 L",
  "sample": "S AE1 M P AH0 L",
  "specimen": "S P EH1 S AH0 M AH0 N",
  "particle": "P AA1 R T AH0 K AH0 L",
  "molecule": "M AA1 L AH0 K Y UW2 L",
  "atom": "AE1 T AH0 M",
  "ion": "AY1 AH0 N",
  "electron": "IH2 L EH1 K T R AA2 N",
  "quantum": "K W AA1 N T AH0 M",
  "liquid": "L IH1 K W IH0 D",
  "fluid": "F L UW1 IH0 D",
  "solid": "S AA1 L AH0 D",
  "synthesise": "S IH1 N TH EH2 S AY2 Z",
  "formation": "F AO1 R M EY2 SH AH0 N",
  "method": "M EH1 TH AH0 D",
  "spectrum": "S P EH1 K T R AH0 M",
  "dimension": "D AY2 M EH1 N SH AH0 N",
  "frequency": "F R IY2 K W AH0 N S IY0",
  "antenna": "AE1 N T EH2 N AH0",
  "circuit": "S ER2 K AH1 T"
};

// CMU音标到IPA音标的映射
const cmuToIpa = {
  'AA0': 'ɑ', 'AA1': 'ɑː', 'AA2': 'ɑ',
  'AE0': 'æ', 'AE1': 'æ', 'AE2': 'æ',
  'AH0': 'ə', 'AH1': 'ʌ', 'AH2': 'ʌ',
  'AO0': 'ɔ', 'AO1': 'ɔː', 'AO2': 'ɔ',
  'AW0': 'aʊ', 'AW1': 'aʊ', 'AW2': 'aʊ',
  'AY0': 'aɪ', 'AY1': 'aɪ', 'AY2': 'aɪ',
  'B': 'b', 'CH': 'tʃ', 'D': 'd', 'DH': 'ð',
  'EH0': 'ɛ', 'EH1': 'ɛ', 'EH2': 'ɛ',
  'ER0': 'ɚ', 'ER1': 'ɜːr', 'ER2': 'ɚ',
  'EY0': 'eɪ', 'EY1': 'eɪ', 'EY2': 'eɪ',
  'F': 'f', 'G': 'ɡ', 'HH': 'h', 'JH': 'dʒ',
  'IH0': 'ɪ', 'IH1': 'ɪ', 'IH2': 'ɪ',
  'IY0': 'i', 'IY1': 'iː', 'IY2': 'i',
  'K': 'k', 'L': 'l', 'M': 'm', 'N': 'n',
  'NG': 'ŋ', 'OW0': 'oʊ', 'OW1': 'oʊ', 'OW2': 'oʊ',
  'OY0': 'ɔɪ', 'OY1': 'ɔɪ', 'OY2': 'ɔɪ',
  'P': 'p', 'R': 'r', 'S': 's', 'SH': 'ʃ',
  'T': 't', 'TH': 'θ', 'UH0': 'ʊ', 'UH1': 'ʊ', 'UH2': 'ʊ',
  'UW0': 'u', 'UW1': 'uː', 'UW2': 'u',
  'V': 'v', 'W': 'w', 'Y': 'j', 'Z': 'z', 'ZH': 'ʒ'
};

/**
 * 将CMU音标转换为IPA音标
 * @param {string} cmuPhonetic - CMU格式的音标
 * @returns {string} IPA格式的音标
 */
const cmuToIpaConverter = (cmuPhonetic) => {
  if (!cmuPhonetic) return '';
  
  return cmuPhonetic.split(' ')
    .map(symbol => cmuToIpa[symbol] || symbol)
    .join('');
};

/**
 * 获取单词的国际音标
 * @param {string} word - 英文单词
 * @returns {string} 国际音标（IPA格式）
 */
export const getPhonetic = (word) => {
  if (!word) return '';
  
  const lowercaseWord = word.toLowerCase();
  const cmuPhonetic = cmuDict[lowercaseWord];
  
  if (cmuPhonetic) {
    const ipaPhonetic = cmuToIpaConverter(cmuPhonetic);
    return `/${ipaPhonetic}/`;
  }
  
  return '';
};
